version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build-and-test:     
    executor:
      name: node/default      
    steps:      
      - checkout
      - node/install-packages:
          app-dir: cdktf-aws-lambda-helloWorld
      - run:
          command: npm run test
          working_directory: cdktf-aws-lambda-helloWorld
         
workflows:
    build-and-test:
      jobs:
        - build-and-test